"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.2.5.
...
"""

from pathlib import Path
import os # REQUIRED for the STATIC_ROOT setting

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#au7)4o$1m^3fum)80d^bu_4lfxy#_v&a6u6hn%hg5&6f!1-!u'

# SECURITY WARNING: don't run with debug turned on in production!
# CRITICAL: MUST BE FALSE FOR LIVE SERVER SECURITY
DEBUG = False

# ALLOWED_HOSTS: CRITICAL SETTING FOR LIVE SITES
# Keep this empty for now. Once you deploy to Render, you MUST update this:
# Example: ALLOWED_HOSTS = ['maluva-vibes.onrender.com']
ALLOWED_HOSTS = ["https://soundshop.onrender.com"]


# Application definition
INSTALLED_APPS = [
    'home',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database settings remain the same
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation settings remain the same


# Internationalization settings remain the same
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# NEW: Defines the folder where static files will be collected for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===============================================
# EMAIL CONFIGURATION (Dummy Backend - No Live Sending)
# ===============================================

# Uses the dummy backend, which accepts the data and displays the success message, 
# but simply discards the email instead of trying to send it live.
EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend' 
DEFAULT_FROM_EMAIL = 'Maluva Vibes Website <no-reply@maluvavibes.com>'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

